### ISSUE TITLE
Replace simple role with spartie role manager

### ISSUE THREAD

**Issue by enjutomojamutote** [rrpadilla/laravel-adminlte-boilerplate#10]
Hi,

How can I remove the simple role with this package??

**Comment by rrpadilla** [comment]
@enjutomojamutote,

This project is using [Laravel policies](https://laravel.com/docs/5.6/authorization#creating-policies) (**recommended**). Even [Laravel Nova](https://nova.laravel.com/) is using this method too.
I do not know how spartie role manager works.
Pretty sure that package is using 5 tables (users, roles, permissions, users_roles and roles_permissions). 
I PREFER a simpler approach. Maybe saving the permissions on a config file or reading directly from policies classes.
In the future we can implement a more advanced/simple permissions package.

Thanks.
