### ISSUE TITLE
Separate Views and File Upload

### ISSUE THREAD

**Issue by carlosiv** [rrpadilla/laravel-adminlte-boilerplate#11]
You have an extensive documentation. But I tried to create Task Controller and subsequent files. But, how do I create views for users (view only created task by logged-in user) and views for admin(all task created by users). Also how do I handle file uploads?

**Comment by rrpadilla** [comment]
hi @carlosiv,
see [Laravel documentation](https://laravel.com/docs/5.6/filesystem#file-uploads) to see how you can handle file upload.
You do not have to create different views for every user role. Try to use policies and check the role/permissions from the same view. See documentation about policy [here](https://github.com/rrpadilla/laravel-adminlte-boilerplate/wiki/Adding-Resources#policy).
This code going to show edit link only when user has permission to edit the resource.
```php
$canUpdate = Auth::user()->can('update', $record);

@if ($canUpdate)
     <a href="{{ $editLink }}">{{ $record->id }}</a>
@else {{ $record->id }} @endif
```

Thanks.
