### ISSUE TITLE
phpunit

### ISSUE THREAD

**Issue by lexy1105** [rrpadilla/laravel-adminlte-boilerplate#12]
Hello
I 'm trying to use this laravel admin code
But when i try write "phpunit" on cmd, I got this result message

"PHPUnit 3.7.21 by Sebastian Bergmann.
Configuration read from F:\Laravel\LAdminLTE\ladminlte\phpunit.xml
Time: 0 seconds, Memory: 4.00Mb
No tests executed!"

Do you have any idea to fix it?
Thanks

**Comment by lexy1105** [comment]
![screenshot_2](https://user-images.githubusercontent.com/30527066/45727391-290f0800-bbf6-11e8-9ec2-69b606dd0021.png)

**Comment by rodruiz** [comment]
@yang511 
make sure you have all requirements installed.
```bash
composer install
composer dump-autoload
```

**Comment by rrpadilla** [comment]
@yang511 added that to the readme. See: [commit](https://github.com/rrpadilla/laravel-adminlte-boilerplate/commit/3add84af4c1f551ce86633eb095575ca5f4c3d37).
Thanks.

**Comment by lexy1105** [comment]
Hello
Still same message "No Tests executed"
Can you check?
Thanks

**Comment by rodruiz** [comment]
Hi @yang511 
the issue could be your phpunit installation, try running this instead:
```bash
./vendor/bin/phpunit -v
```
Let me know if that works for you.

**Comment by lexy1105** [comment]
OK, thanks let me try
