### ISSUE TITLE
Can you explain a bit about AdminAccess middleware? How can it be without guard? I just confused

### ISSUE THREAD

**Issue by handhikadj** [rrpadilla/laravel-adminlte-boilerplate#16]
### This is not an issue, other than an explanation

Hey rrpadilla, thank you for this package anyway

I just want to ask what does the middleware AdminAccess do? It goes without any `admin` on config/auth.php guard while the third argument is specified. Can you help a brother out?

Thank you

**Comment by rrpadilla** [comment]
Hi @handhikadj,
that's a good question.

AdminAccess Middleware is checking if current user is administrator. Going to redirect the user to the dashboard or return a 401 response if is not an admin. There is a method "isAdmin()" in User model to check this. 
For example when you want to use the "users" table for users only and "admins" table for "administrators" only you will use a different guard like "admin" in "config/auth.php". A provider defines how the users are actually retrieved out of your database. 
```php
// Route using "admin" guard. AdminAccess will user the guard "admin"
Route::group(['middleware' => 'admin:admin'], function () {
   // routes here
});
```


```php
// AdminAccess Middleware
if (Auth::guard($guard)->check()) {
        if (Auth::guard($guard)->user()->isAdmin()) {
                return $next($request);
        }
}
```
```php
// User Model.
/**
* @return boolean
*/
public function isAdmin()
{
        return (int) $this->is_admin === 1;
}
```

Let me know if you understand now.

Thanks.

**Comment by handhikadj** [comment]
So the `$guard = null` on `handle()` method is just a (sort of) boilerplate for another guard, isn't it?

**Comment by rrpadilla** [comment]
Correct, if no guard provided will use the default guard in [config/auth.php](https://github.com/rrpadilla/laravel-adminlte-boilerplate/blob/master/config/auth.php#L16-L19)

**Comment by handhikadj** [comment]
Ok. thanks. case closed

**Comment by rrpadilla** [comment]
@handhikadj,
if you like this boilerplate, please, add a star.
Thanks.
