### ISSUE TITLE
How to implement Datatable with server side sort.

### ISSUE THREAD

**Issue by billion102** [rrpadilla/laravel-adminlte-boilerplate#17]
Hello.
Your framework is best. But I am not sure how to implement server side sort in list view.
Sort is working on current page.
I want to sort with all record.
![Screenshot_2](https://user-images.githubusercontent.com/16626747/64797145-7af13080-d5b3-11e9-9f0c-b294a82bf538.png)

please help me.

**Comment by rrpadilla** [comment]
Hi @billion102,
for example if you want to do it in **UsersController** you can update the [getSearchRecords](https://github.com/rrpadilla/laravel-adminlte-boilerplate/blob/master/app/Http/Controllers/Admin/UsersController.php#L139-L146) method.
```php
    private function getSearchRecords(Request $request, $perPage = 15, $search = null)
    {
        $sortBy = $request->input('sort_by', '');

        return $this->getResourceModel()::when(! empty($search), function ($query) use ($search) {
            $query->where(function ($query) use ($search) {
                $query->where('name', 'like', "%$search%")
                    ->orWhere('email', 'like', "%$search%");
            });
        })->when(! empty($sortBy), function ($query) use ($sortBy) {
            $query->orderBy($sortBy, 'desc');
        })->paginate($perPage);
    }
```
