### ISSUE TITLE
ERROR load css js

### ISSUE THREAD

**Issue by i-coder** [rrpadilla/laravel-adminlte-boilerplate#2]
![image](https://user-images.githubusercontent.com/1822215/38658682-95b99d10-3e3f-11e8-954f-b230a4af43c3.png)

**Comment by rrpadilla** [comment]
Hi @i-coder,
you are using "homestead.test" to access your site. You have to set the APP_URL environment variable in your .env file. 
```txt
APP_URL=http://homestead.test
```
Let me know if that works for you.
Thanks.
