### ISSUE TITLE
Vendor Dir

### ISSUE THREAD

**Issue by anaether** [rrpadilla/laravel-adminlte-boilerplate#3]
Hi, 
when someone wants to use your modified script, then he will safe abort by the part with php artisan key:generate because you dont have uploaded the vendor directory.

Good Regards, 
cRUSHER

**Comment by rodruiz** [comment]
Hi @cRUSHER-HLG,
did you follow the How to Use steps?
- when you run "composer install" command, composer will download all dependencies and the vendor directory will be created.

Thanks.

**Comment by anaether** [comment]
@rodruiz okey its working dont saw the commands at bottom. Now its running well. Its a nice script to extend it on your own purpose :D. Thanks for it and your work <3
