### ISSUE TITLE
Witdh-767 Problem

### ISSUE THREAD

**Issue by anaether** [rrpadilla/laravel-adminlte-boilerplate#4]
Hi, 
I have installed your edition of laravel with adminlte because its clean and dont contains stuff that i dont need/want. Now i want to customize the page but i have the problem, that when i scale firefox/chrome under 767px the navbar right items dont are lined to right. Its a filed empty but this i dont want. If you do the same with the default adminlte design then its not. 
Here a pic that you see what i mean: 
![pic1](https://user-images.githubusercontent.com/35463368/39398881-dd503c88-4b14-11e8-96a6-fcbe257128d3.PNG)

And if i put it more less then it looks so: 
![pic2](https://user-images.githubusercontent.com/35463368/39398959-dadbac2a-4b15-11e8-89bc-bccae1e2113d.PNG)

At the position where i colored it i want to be the first position of the right element to remove the space there. If its over 768px it works great.

For the first pic (I want it in this way):
![pic11](https://user-images.githubusercontent.com/35463368/39398999-76f3ad42-4b16-11e8-9890-0a151c7ed121.PNG)

Fort the second pic so i want it:
![pic22](https://user-images.githubusercontent.com/35463368/39399002-7ed9eada-4b16-11e8-823c-3dd6556e1d2c.PNG)

**Comment by anaether** [comment]
Okey. Maybe also others have this problem. I post the solution because it will be usefull for others. 
The problem exists already with the default if you download it. I have tried it out before some mins. 
Now in every size in chrome/firefox it works like in the original adminlte template.
My solution was now to remove this: 
```
<!-- Collect the nav links, forms, and other content for toggling
<div class="collapse navbar-collapse pull-left" id="navbar-collapse">
     <ul class="nav navbar-nav">
          <li><a href="/">Links</a></li>
     </ul>
</div>-->
```

Pls also update it in the repo that it works correctly

**Comment by rrpadilla** [comment]
Hi,
Could yo submit a PR to fix it?

Thanks.
