### ISSUE TITLE
403, Forbidden

### ISSUE THREAD

**Issue by hung4564** [rrpadilla/laravel-adminlte-boilerplate#6]
i am a newbie in laravel. sorry for my bad english.
how do i add category manager??
i had copy from all file has name 'user' and change to category but when i go to it, it show error 403?
this is my code :https://github.com/hung4564/test.

**Comment by senninrico** [comment]
Same... What to do for this ?

**Comment by rrpadilla** [comment]
Hi,
Could you explain in more details what are you trying to do?
Thanks.

**Comment by senninrico** [comment]
Hi , i need create new module in admin but i don't have knwohow to this. Iam newbie in laravel ...this is my first project.
I created a similar user files of admin and retrive in console 

> This  action is unauthorized.C:\xampp\htdocs\a1\vendor\laravel\framework\src\Illuminate\Auth\Access\HandlesAuthorization.php#2

**Comment by rodruiz** [comment]
Hi @senninrico,
just follow the documentation [Adding Resources](https://github.com/rrpadilla/laravel-adminlte-boilerplate/wiki/Adding-Resources).

Thanks.

**Comment by senninrico** [comment]
tks
