### ISSUE TITLE
Don't show adninLTE

### ISSUE THREAD

**Issue by ogugus** [rrpadilla/laravel-adminlte-boilerplate#7]
<img width="1280" alt="captura de tela 2018-06-07 as 07 31 45" src="https://user-images.githubusercontent.com/25387859/41094524-ec7dab30-6a24-11e8-9c02-6091a25eba42.png">

**Comment by rodruiz** [comment]
Hi @ogugus,
You have to set the APP_URL environment variable in your .env file.
```config
APP_URL=http://homestead.test
```

Thanks.
