### ISSUE TITLE
Not working on fresh install in ubuntu

### ISSUE THREAD

**Issue by enjutomojamutote** [rrpadilla/laravel-adminlte-boilerplate#9]
Hi
I just made a fresh install of laravel 5.2 + php 7.2 and cant make it work. I follow the instructions: 

- [ ] Clone: git clone https://github.com/rrpadilla/laravel-adminlte-boilerplate.git my-new-project
- [ ] cd my-new-project
- [ ] Copy .env.example file to .env and edit database credentials and APP_URL
- [ ] Run composer install
- [ ] Run php artisan key:generate
- [ ] Run php artisan migrate --seed

But when I access to public direct throw browser only show. the top of the bar without the form. And when I click login or register. Just an 404....

**Comment by rodruiz** [comment]
Hi @enjutomojamutote,
what do you mean with "fresh install of laravel 5.2"?
You have to clone this project. This is a modified version of laravel 5.6 with some extra features.

**Comment by enjutomojamutote** [comment]
Hi thanks for answer. I just can run the packet though php artisan serve... The question is how can i run the packet in a vps for example. Because I mean my laravel doesnt work well cloning the project...

**Comment by rrpadilla** [comment]
You have to check laravel documentation to see how you can deploy a laravel
app.
See link below:
https://laravel.com/docs/5.6/deployment

Thanks.
